version: 0.1
phases:
  install:
    commands:
      - wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      - "echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' >> \
          /etc/apt/sources.list.d/google.list"
      - apt-get update
      - apt-get install -y --no-install-recommends default-jre google-chrome-stable jq
      - npm install
      - chmod -R +x scripts/
  pre_build:
    commands:
      - npm run lint
      - npm run api:ci
      - npm run test:once
      - npm run e2e
  build:
    commands:
      - npm run build:prod
  post_build:
    commands:
      - aws s3 sync dist/ s3://${WEB_BUCKET}/ --exclude index.html
      - aws s3 cp dist/index.html s3://${WEB_BUCKET}/
