version: 0.1
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm run api ${API_ID} ${API_STAGE}
      - npm run headless test:once e2e lint
  build:
    commands:
      - npm run build:prod
      - aws s3 sync dist s3://${ARTIFACTS_BUCKET}/${ARTIFACTS_PREFIX}