version: 0.1
phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y --no-install-recommends xvfb
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - dpkg -i google-chrome-stable_current_amd64.deb
      - npm install
  pre_build:
    commands:
      - npm run headless test:once e2e lint
  build:
    commands:
      - npm run build:prod
  post_build:
    commands:
      - aws s3 sync dist/ s3://${WEB_BUCKET}/app/ --exclude index.html