version: 0.1
phases:
  install:
    commands:
      - wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      - "echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' >> \
          /etc/apt/sources.list.d/google.list"
      - apt-get update
      - apt-get install -y --no-install-recommends google-chrome-stable xvfb
      - npm install
  pre_build:
    commands:
      - xvfb-run -a run-s test:once e2e lint
  build:
    commands:
      - npm run build:prod
  post_build:
    commands:
      - aws s3 sync dist/ s3://${WEB_BUCKET}/app/ --exclude index.html